CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "Donors" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" character varying(100) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "BloodType" text NOT NULL,
        "LastDonationDate" date,
        "DateOfBirth" date NOT NULL,
        "NIN" character varying(20) NOT NULL,
        "PhoneNumber" character varying(15) NOT NULL,
        "Address" character varying(200) NOT NULL,
        "NotesBTC" text,
        CONSTRAINT "PK_Donors" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "GlobalStocks" (
        "BloodType" text NOT NULL,
        "BloodBagType" text NOT NULL,
        "CountExpired" integer NOT NULL,
        "CountExpiring" integer NOT NULL,
        "ReadyCount" integer NOT NULL,
        "MinStock" integer NOT NULL,
        "CriticalStock" integer NOT NULL,
        CONSTRAINT "PK_GlobalStocks" PRIMARY KEY ("BloodType", "BloodBagType")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "Notifications" (
        "Id" uuid NOT NULL,
        "Title" character varying(100) NOT NULL,
        "Message" character varying(500) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsRead" boolean NOT NULL DEFAULT FALSE,
        "UserId" uuid,
        "Link" character varying(255),
        "Icon" character varying(255),
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "PushSubscriptions" (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "Endpoint" character varying(500) NOT NULL,
        "P256dh" character varying(500) NOT NULL,
        "Auth" character varying(500) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastModifiedAt" timestamp with time zone,
        CONSTRAINT "PK_PushSubscriptions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "Services" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Email" text NOT NULL,
        "Password" character varying(50) NOT NULL,
        "Role" text NOT NULL,
        "DateOfBirth" timestamp with time zone NOT NULL,
        "PhoneNumber" character varying(10) NOT NULL,
        "Address" text NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "Wilayas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_Wilayas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "Requests" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "BloodType" text NOT NULL,
        "Priority" text NOT NULL,
        "BloodBagType" text NOT NULL,
        "RequestDate" date NOT NULL,
        "DueDate" date,
        "Status" text NOT NULL,
        "MoreDetails" character varying(500),
        "RequiredQty" integer NOT NULL,
        "AquiredQty" integer NOT NULL,
        "autoResolve" boolean NOT NULL,
        "ServiceId" uuid,
        "DonorId" uuid,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Requests_Donors_DonorId" FOREIGN KEY ("DonorId") REFERENCES "Donors" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Requests_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "BloodTransferCenters" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" character varying(100) NOT NULL,
        "Address" character varying(200) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "PhoneNumber" character varying(20) NOT NULL,
        "IsPrimary" boolean NOT NULL DEFAULT FALSE,
        "WilayaId" integer NOT NULL,
        CONSTRAINT "PK_BloodTransferCenters" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BloodTransferCenters_Wilayas_WilayaId" FOREIGN KEY ("WilayaId") REFERENCES "Wilayas" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "Communes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "WilayaId" integer NOT NULL,
        CONSTRAINT "PK_Communes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Communes_Wilayas_WilayaId" FOREIGN KEY ("WilayaId") REFERENCES "Wilayas" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "BloodBags" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "BloodBagType" text NOT NULL,
        "BloodType" text NOT NULL,
        "Status" text NOT NULL,
        "ExpirationDate" date NOT NULL,
        "AcquiredDate" date NOT NULL,
        "DonorId" uuid,
        "RequestId" uuid,
        CONSTRAINT "PK_BloodBags" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BloodBags_Donors_DonorId" FOREIGN KEY ("DonorId") REFERENCES "Donors" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_BloodBags_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE TABLE "Pledges" (
        "DonorId" uuid NOT NULL,
        "RequestId" uuid NOT NULL,
        "FulfillmentDate" date,
        "Status" character varying(20) NOT NULL,
        "PledgeDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Pledges" PRIMARY KEY ("DonorId", "RequestId"),
        CONSTRAINT "FK_Pledges_Donors_DonorId" FOREIGN KEY ("DonorId") REFERENCES "Donors" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Pledges_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_BloodBags_DonorId" ON "BloodBags" ("DonorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_BloodBags_RequestId" ON "BloodBags" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_BloodTransferCenters_Email" ON "BloodTransferCenters" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE UNIQUE INDEX "IX_BloodTransferCenters_IsPrimary" ON "BloodTransferCenters" ("IsPrimary") WHERE "IsPrimary" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE UNIQUE INDEX "IX_BloodTransferCenters_Name" ON "BloodTransferCenters" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_BloodTransferCenters_WilayaId" ON "BloodTransferCenters" ("WilayaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_Communes_WilayaId" ON "Communes" ("WilayaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_Notifications_CreatedAt" ON "Notifications" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_Notifications_IsRead" ON "Notifications" ("IsRead");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_Pledges_RequestId" ON "Pledges" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE UNIQUE INDEX "IX_PushSubscriptions_Endpoint" ON "PushSubscriptions" ("Endpoint");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_PushSubscriptions_UserId" ON "PushSubscriptions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_Requests_DonorId" ON "Requests" ("DonorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE INDEX "IX_Requests_ServiceId" ON "Requests" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE UNIQUE INDEX "IX_Services_Name" ON "Services" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    CREATE UNIQUE INDEX "IX_Users_Name" ON "Users" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250529174121_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250529174121_Initial', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531200540_AddSoftDeleteAndUpdatedEntities') THEN
    ALTER TABLE "BloodBags" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531200540_AddSoftDeleteAndUpdatedEntities') THEN
    ALTER TABLE "BloodTransferCenters" ADD CONSTRAINT "CK_SingleBloodTransferCenter" CHECK (1=(SELECT CASE WHEN COUNT(*) <= 1 THEN 1 ELSE 0 END FROM "BloodTransferCenters"));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531200540_AddSoftDeleteAndUpdatedEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250531200540_AddSoftDeleteAndUpdatedEntities', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531202218_FixSingleBloodTransferCenterConstraint') THEN
    ALTER TABLE "BloodTransferCenters" DROP CONSTRAINT "CK_SingleBloodTransferCenter";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531202218_FixSingleBloodTransferCenterConstraint') THEN
    ALTER TABLE "BloodTransferCenters" ADD "SingletonCheck" integer NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531202218_FixSingleBloodTransferCenterConstraint') THEN
    CREATE UNIQUE INDEX "IX_BloodTransferCenters_SingletonCheck" ON "BloodTransferCenters" ("SingletonCheck");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531202218_FixSingleBloodTransferCenterConstraint') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250531202218_FixSingleBloodTransferCenterConstraint', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531202503_FixBTCConstraintV2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250531202503_FixBTCConstraintV2', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531204300_FixBloodTransferCenterConstraint') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250531204300_FixBloodTransferCenterConstraint', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531205831_FixBloodTransferCenterConstraintFinal') THEN
    ALTER TABLE "BloodTransferCenters" DROP CONSTRAINT IF EXISTS "CK_SingleBloodTransferCenter";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531205831_FixBloodTransferCenterConstraintFinal') THEN

                    DO $$ 
                    BEGIN
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                      WHERE table_name = 'BloodTransferCenters' 
                                      AND column_name = 'SingletonCheck') THEN
                            ALTER TABLE "BloodTransferCenters" ADD COLUMN "SingletonCheck" INTEGER NOT NULL DEFAULT 1;
                        END IF;
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531205831_FixBloodTransferCenterConstraintFinal') THEN

                    DO $$
                    BEGIN
                        IF NOT EXISTS (SELECT 1 FROM pg_indexes 
                                      WHERE tablename = 'BloodTransferCenters' 
                                      AND indexname = 'IX_BloodTransferCenters_SingletonCheck') THEN
                            CREATE UNIQUE INDEX "IX_BloodTransferCenters_SingletonCheck" ON "BloodTransferCenters" ("SingletonCheck");
                        END IF;
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250531205831_FixBloodTransferCenterConstraintFinal') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250531205831_FixBloodTransferCenterConstraintFinal', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250601024811_newMIGRATIONS') THEN
    ALTER TABLE "Pledges" DROP COLUMN "FulfillmentDate";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250601024811_newMIGRATIONS') THEN
    ALTER TABLE "Pledges" ALTER COLUMN "PledgeDate" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250601024811_newMIGRATIONS') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250601024811_newMIGRATIONS', '9.0.4');
    END IF;
END $EF$;
COMMIT;

