CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "Contributors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Status" integer NOT NULL,
        "PhoneNumber_CountryCode" text,
        "PhoneNumber_Number" text,
        "PhoneNumber_Extension" text,
        CONSTRAINT "PK_Contributors" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "Wilayas" (
        "Id" integer NOT NULL,
        "Nom" text NOT NULL,
        CONSTRAINT "PK_Wilayas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "BloodTansfusionCenters" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Address" text,
        "Contact" text,
        "Email" text,
        "Tel" text,
        "WilayaId" integer NOT NULL,
        CONSTRAINT "PK_BloodTansfusionCenters" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BloodTansfusionCenters_Wilayas_WilayaId" FOREIGN KEY ("WilayaId") REFERENCES "Wilayas" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "Communes" (
        "Id" integer NOT NULL,
        "Nom" text NOT NULL,
        "WilayaId" integer NOT NULL,
        CONSTRAINT "PK_Communes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Communes_Wilayas_WilayaId" FOREIGN KEY ("WilayaId") REFERENCES "Wilayas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "BloodDonationRequests" (
        "Id" uuid NOT NULL,
        "EvolutionStatus" integer NOT NULL,
        "DonationType" integer NOT NULL,
        "BloodGroup" integer NOT NULL,
        "RequestedQty" integer NOT NULL,
        "RequestDate" timestamp with time zone NOT NULL,
        "RequestDueDate" timestamp with time zone,
        "Priority" integer NOT NULL,
        "MoreDetails" text,
        "ServiceName" text,
        "BloodTansfusionCenterId" uuid NOT NULL,
        CONSTRAINT "PK_BloodDonationRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BloodDonationRequests_BloodTansfusionCenters_BloodTansfusio~" FOREIGN KEY ("BloodTansfusionCenterId") REFERENCES "BloodTansfusionCenters" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "BloodInventories" (
        "Id" uuid NOT NULL,
        "BloodTansfusionCenterId" uuid NOT NULL,
        "BloodGroup" integer NOT NULL,
        "BloodDonationType" integer NOT NULL,
        "TotalQty" integer,
        "MinQty" integer,
        "MaxQty" integer,
        CONSTRAINT "PK_BloodInventories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BloodInventories_BloodTansfusionCenters_BloodTansfusionCent~" FOREIGN KEY ("BloodTansfusionCenterId") REFERENCES "BloodTansfusionCenters" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "IsAdmin" boolean NOT NULL,
        "DonorWantToStayAnonymous" boolean NOT NULL,
        "DonorExcludeFromPublicPortal" boolean NOT NULL,
        "DonorAvailability" integer,
        "DonorContactMethod" integer,
        "DonorName" text NOT NULL,
        "DonorBirthDate" timestamp with time zone NOT NULL,
        "DonorBloodGroup" integer NOT NULL,
        "DonorNIN" text NOT NULL,
        "DonorTel" text,
        "DonorNotesForBTC" text,
        "DonorLastDonationDate" timestamp with time zone,
        "CommuneId" integer,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUsers_Communes_CommuneId" FOREIGN KEY ("CommuneId") REFERENCES "Communes" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "BloodDonationPledges" (
        "Id" uuid NOT NULL,
        "EvolutionStatus" integer NOT NULL,
        "PledgeInitiatedDate" timestamp with time zone NOT NULL,
        "PledgeDate" timestamp with time zone,
        "PledgeHonoredOrCanceledDate" timestamp with time zone,
        "PledgeNotes" text,
        "CantBeDoneReason" text,
        "BloodDonationRequestId" uuid NOT NULL,
        "ApplicationUserId" uuid NOT NULL,
        CONSTRAINT "PK_BloodDonationPledges" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BloodDonationPledges_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_BloodDonationPledges_BloodDonationRequests_BloodDonationReq~" FOREIGN KEY ("BloodDonationRequestId") REFERENCES "BloodDonationRequests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE TABLE "DonorBloodTransferCenterSubscriptions" (
        "Id" uuid NOT NULL,
        "BloodTansfusionCenterId" uuid NOT NULL,
        "ApplicationUserId" uuid NOT NULL,
        CONSTRAINT "PK_DonorBloodTransferCenterSubscriptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DonorBloodTransferCenterSubscriptions_AspNetUsers_Applicati~" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DonorBloodTransferCenterSubscriptions_BloodTansfusionCenter~" FOREIGN KEY ("BloodTansfusionCenterId") REFERENCES "BloodTansfusionCenters" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_AspNetUsers_CommuneId" ON "AspNetUsers" ("CommuneId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_BloodDonationPledges_ApplicationUserId" ON "BloodDonationPledges" ("ApplicationUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_BloodDonationPledges_BloodDonationRequestId" ON "BloodDonationPledges" ("BloodDonationRequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_BloodDonationRequests_BloodTansfusionCenterId" ON "BloodDonationRequests" ("BloodTansfusionCenterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_BloodInventories_BloodTansfusionCenterId" ON "BloodInventories" ("BloodTansfusionCenterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_BloodTansfusionCenters_WilayaId" ON "BloodTansfusionCenters" ("WilayaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_Communes_WilayaId" ON "Communes" ("WilayaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_DonorBloodTransferCenterSubscriptions_ApplicationUserId" ON "DonorBloodTransferCenterSubscriptions" ("ApplicationUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    CREATE INDEX "IX_DonorBloodTransferCenterSubscriptions_BloodTansfusionCenter~" ON "DonorBloodTransferCenterSubscriptions" ("BloodTansfusionCenterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521111908_MigrationName') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250521111908_MigrationName', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521171411_QuickFix') THEN
    ALTER TABLE "Wilayas" RENAME COLUMN "Nom" TO "Name";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521171411_QuickFix') THEN
    ALTER TABLE "Communes" RENAME COLUMN "Nom" TO "Name";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521171411_QuickFix') THEN
    ALTER TABLE "BloodDonationRequests" ALTER COLUMN "EvolutionStatus" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521171411_QuickFix') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250521171411_QuickFix', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521181957_DonnorCorrelationID') THEN
    ALTER TABLE "AspNetUsers" ADD "CorrelationId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521181957_DonnorCorrelationID') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250521181957_DonnorCorrelationID', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250522080909_UsersFixes') THEN
    ALTER TABLE "AspNetUsers" DROP COLUMN "IsAdmin";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250522080909_UsersFixes') THEN
    ALTER TABLE "AspNetUsers" RENAME COLUMN "CorrelationId" TO "DonorCorrelationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250522080909_UsersFixes') THEN
    ALTER TABLE "AspNetUsers" ALTER COLUMN "DonorWantToStayAnonymous" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250522080909_UsersFixes') THEN
    ALTER TABLE "AspNetUsers" ALTER COLUMN "DonorExcludeFromPublicPortal" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250522080909_UsersFixes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250522080909_UsersFixes', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250522203303_InitA') THEN
    DROP TABLE "BloodInventories";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250522203303_InitA') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250522203303_InitA', '9.0.4');
    END IF;
END $EF$;
COMMIT;

